### ISSUE TITLE
Crash when switching to the "Parameter Variability" tab

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#16]
The app gives an error when directly switching to the "Parameter Variability" tab

```
Traceback (most recent call last):
  File "/home/rikard/devel/modelbuilder/app.py", line 440, in render_iiv_iov_data
    occ_opts = globals()["model"].datainfo.typeix["idv"].names + globals()["model"].datainfo.typeix["unknown"].names
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/model/datainfo.py", line 1008, in __getitem__
    raise IndexError(f"No columns of type {i} available")
IndexError: No columns of type idv available

During handling of the above exception, another exception occurred:

IndexError: No columns of type unknown available
```

**Comment by davsjob** [comment]
Great find! As of now it's because it tries to load a dataset with none provided.

**Comment by davsjob** [comment]
Resolved!
