### ISSUE TITLE
Crash when directly switching to MM elimination

### ISSUE THREAD

**Issue by rikardn** [pharmpy/modelbuilder#17]
Directly switching to MM elimination after starting the app causes a crash.

I think this is actually a bug in Pharmpy:

```
Traceback (most recent call last):
  File "/home/rikard/devel/modelbuilder/app.py", line 174, in update_abs_elim
    "MM": set_michaelis_menten_elimination(globals()["model"]),
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/modeling/odes.py", line 573, in set_michaelis_menten_elimination
    model = _do_michaelis_menten_elimination(model)
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/modeling/odes.py", line 645, in _do_michaelis_menten_elimination
    km_init, clmm_init = _get_mm_inits(model, numer, combined)
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/modeling/odes.py", line 753, in _get_mm_inits
    dv_max = get_observations(model).max()
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/modeling/data.py", line 257, in get_observations
    idcol = model.datainfo.id_column.name
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/model/datainfo.py", line 738, in id_column
    return self.typeix['id'][0]
  File "/home/rikard/devel/modelbuilder_venv/lib/python3.10/site-packages/pharmpy/model/datainfo.py", line 1008, in __getitem__
    raise IndexError(f"No columns of type {i} available")
IndexError: No columns of type id available
```

**Comment by davsjob** [comment]
I think this error is caused when trying to update a model with no dataset associated, setting a dataset before fixes the issue

**Comment by rikardn** [comment]
Ok, in that case it is a bug in Pharmpy. I will open an issue there

**Comment by rikardn** [comment]
Upstream report: https://github.com/pharmpy/pharmpy/issues/1994

**Comment by rikardn** [comment]
I fixed this in Pharmpy. We can close this when it has been tested to work here.
